### ISSUE TITLE
Error: Exception while invoking method 

### ISSUE THREAD

**Issue by radojko** [hwillson/meteor-solr-demo#14]
I have this error with Meteor afer starting app with command meteor:

App running at: http://localhost:3000/
I20160605-10:19:34.417(2)? Exception while invoking method 'App.methods.autosuggest.getSuggestions' Error: url must be absolute and start with http:// or https://
I20160605-10:19:34.418(2)?     at Object._call (packages/http/httpcall_server.js:35:1)
I20160605-10:19:34.418(2)?     at Object.call (packages/meteor/helpers.js:118:1)
I20160605-10:19:34.418(2)?     at Object.HTTP.get (packages/http/httpcall_common.js:50:1)
I20160605-10:19:34.418(2)?     at [object Object].App.methods.autosuggest.getSuggestions.ValidatedMethod.run (lib/methods/autosuggest.js:12:31)
I20160605-10:19:34.418(2)?     at ValidatedMethod._execute (validated-method.js:87:43)
I20160605-10:19:34.418(2)?     at [object Object].ValidatedMethod.connection.methods._connection$methods.(anonymous function) (validated-method.js:37:23)
I20160605-10:19:34.418(2)?     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
I20160605-10:19:34.419(2)?     at livedata_server.js:708:19
I20160605-10:19:34.419(2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160605-10:19:34.419(2)?     at livedata_server.js:706:40
I20160605-10:19:34.758(2)? Exception while invoking method 'search.source' TypeError: Cannot call method 'join' of undefined
I20160605-10:19:34.759(2)?     at Query.fl.Query.restrict (/Medicom/meteor/meteor-solr-demo/.meteor/local/isopacks/npm-container/npm/node_modules/solr-client/lib/query.js:277:27)
I20160605-10:19:34.759(2)?     at Object.SearchQuery.buildSearchQuery (lib/models/search_query.js:46:11)
I20160605-10:19:34.759(2)?     at [object Object].<anonymous> (server/search.js:19:19)
I20160605-10:19:34.759(2)?     at [object Object].getSourceData (packages/meteorhacks_search-source/lib/server.js:65:1)
I20160605-10:19:34.759(2)?     at [object Object].Meteor.methods.search.source (packages/meteorhacks_search-source/lib/server.js:18:1)
I20160605-10:19:34.760(2)?     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
I20160605-10:19:34.760(2)?     at livedata_server.js:708:19
I20160605-10:19:34.760(2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160605-10:19:34.761(2)?     at livedata_server.js:706:40
I20160605-10:19:34.762(2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)

**Comment by hwillson** [comment]
Looks like the settings.json file isn't being used. Are you starting the app like:

```
meteor --settings=deploy/settings.json
```

**Comment by radojko** [comment]
It works now!

Thanks :)
